# Generated by Django 5.0 on 2024-02-03 06:02

import django_resized.forms
import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=75, scale=0.5, size=[1920, 1080], upload_to=user.models.get_avatar_path),
        ),
    ]
